[package]
name = "whitespine"
authors = ["Miloslav Macurek"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chess = "3.2.0"
cmdr = "0.3.12"
rand = "0.8.5"
