[package]
name = "whitespine"
authors = ["Miloslav Mac≈Ørek"]
version = "1.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chess = "3.2.0"
